submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/CMakeLists_file_fix
    git_commit: 66cb82bd45ea8269e0260b26524696ff75398c02 

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/CMakeLists_file_fix
    git_commit: c96bbfb1445d5140d523485dfabf95bcadf6c1e9

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/CMakeLists_file_fix
    git_commit: 2509c84714d5c9a7ed5c16115013787803a2d3ba
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/CMakeLists_file_fix
    git_commit: f03f5a2ad201e4145eb12a293e2898bcf12ae6ac