submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/main
    git_commit: d55eb2b7dea6e0fd946853bed39f2ffc12fa1ecd 

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/main
    git_commit: 2be84f07f9f8f22ff93ff39c605668a7c3036ef3

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/main
    git_commit: c6a32ee104f931db9277b98a236cc45a3d67e865
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/init_map_threadpool
    git_commit: 2a0123378b158d76c475b314ac900c967d7f32d5