submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/init_statemachine
    git_commit: ef94ee5b55d63d79a4105d01e955492e22fbeb60 

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/init_statemachine
    git_commit: c5cf01677ddca8cf0cd1e4080a77742f6da9774a

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/main
    git_commit: c6a32ee104f931db9277b98a236cc45a3d67e865
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/init_map_threadpool
    git_commit: 67c98b632621c33984ebe8cd1310cae71b38d44a