submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/CMakeLists_file_fix
    git_commit: 837d9c2c54914013885b1d60379e7a16dfad93dc 

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/CMakeLists_file_fix
    git_commit: c96bbfb1445d5140d523485dfabf95bcadf6c1e9

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/CMakeLists_file_fix
    git_commit: 7aaa5d01e4f9cfda1d2cdd6f2cec6c936063760c
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/CMakeLists_file_fix
    git_commit: d103a62db86ef8fbeeab50272545e61a96e13d02