submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/main
    git_commit: 9cbf4e827364a254ebe98eb1cd7fd59e48fe329b 

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/main
    git_commit: 652f72aeb712735095ec4dbf2c5a29881354c0af

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/main
    git_commit: 980af71c19f25d04f45571fe881a3137cd079aa7
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/main
    git_commit: 2e33d81490b5c7d7adf121b7f8ee8cf7c87d6131