submodules:
  - name: Imagine_Muduo
    git_url: git@github.com:ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/update_format
    git_commit: 333255a4a6baf9138551bda228033b7c906860f2

  - name: Imagine_ZooKeeper
    git_url: git@github.com:ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/update_format
    git_commit: fda2948467e770d0a5f52da61c4cdcbf36032a13

  - name: Imagine_Rpc
    git_url: git@github.com:ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/update_format
    git_commit: fefeb61cf9b2ef32d43314819e80dfe130c9fe48
  
  - name: Imagine_MapReduce
    git_url: git@github.com:ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/update_format
    git_commit: 41c6016903c56e85895d173e059f3a86fb0b66cb