submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/CMakeLists_file_fix
    git_commit: 4414ae34e631de0c0289f8ee0a3738169b772377 

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/CMakeLists_file_fix
    git_commit: f23c6bcc1622f631596c571d2940a8de68249773

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/CMakeLists_file_fix
    git_commit: 8b4941f89c4295c320d75d6869b40b1680aefe30
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/CMakeLists_file_fix
    git_commit: 78443a33883976081012ce541fd86ea013a62caa