submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/update_interface
    git_commit: ec73de39408dd2711ea5d81d89e4cdeb85dd001d

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/update_interface
    git_commit: 702fa647ef5322a44d9d327227e0cf28544a14a8

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/main
    git_commit: 2e9b7303fa3c5df0d72a2fe54bf2c7743fd73b4d
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/main
    git_commit: 451b535bf8fb7b824ef9f63797dc80ee73a8ed1b