submodules:
  - name: Imagine_Tool
    git_url: https://github.com/ImagineJHY/Imagine_Tool.git
    git_branch: ImagineTool/main
    git_commit: ffb985f5c4cbb84926856f05a852a636e8024c6c
    
  - name: Imagine_Muduo
    git_url: git@github.com:ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/update_code
    git_commit: 38a00a75baf4175c49e7fad8846f0de8ec5cc442

  - name: Imagine_ZooKeeper
    git_url: git@github.com:ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/adapt_tool
    git_commit: 6153f672997cbe7ea3f7538a3d9027c4e65d8bbd

  - name: Imagine_Rpc
    git_url: git@github.com:ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/update_format
    git_commit: a6b4746f43ed346d881db36300ec38ba0bbdf1b8
  
  - name: Imagine_MapReduce
    git_url: git@github.com:ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/update_format
    git_commit: 01eb5390494053fd593f8bc122929b6a04f17941