submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/CMakeLists_file_fix
    git_commit: 69d89416eeeff95ce70afa3018a3b3dd847b0d13 

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/CMakeLists_file_fix
    git_commit: b1435688eed6cac1e166bd46914c88fa0b496e0b

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/CMakeLists_file_fix
    git_commit: 0c5a901127c52ada7c7d5138cfd90416eaf541e2
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/CMakeLists_file_fix
    git_commit: 78443a33883976081012ce541fd86ea013a62caa