submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/test_bug_fix
    git_commit: 59ec594ca1e7c13b24826e084c53e55082840ec6 

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/main
    git_commit: 167dd3b439362e1c3eec3d8e64d4eabe284b5953

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/test_bug_fix
    git_commit: f5e20da82d7739decc1ec8aec9446370e10a5bf3
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/test_bug_fix
    git_commit: 8302a7205f991ae45d39f90b406933f7da9a76b9