submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/main
    git_commit: f10905f06b0d03d0413db9e104bc4d17818bd045 

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/main
    git_commit: 167dd3b439362e1c3eec3d8e64d4eabe284b5953

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/main
    git_commit: 44b4fb25f691113d5f3d2830c11391a5e2d07066
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/main
    git_commit: 9ab248331403c6630cbc0f5431703f8a1b6df0f1