submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/update_code
    git_commit: bd7d10fe720535c4c3a372a3c9eda9d7111433ba

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/adapt_tool
    git_commit: 700f18af7f7ae94f71da86448d39dbdcf58e864e

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/adapt_tool
    git_commit: 44664af017b1339cd643aa838dc8c39d8e21a449
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/adapt_tool
    git_commit: ad18f7c7d0ad64f05a1db8ead5506de35aeaa2d5