submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/update_format
    git_commit: 0666eac8211d5f227afffdcde99c5ec7141e7f1b

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/update_format
    git_commit: 89f1b9f473a73d57fd6405b0706bd048fed0d355

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/update_format
    git_commit: 32b657ef5b4ae45537ba1028c520e6c2c8ee1904
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/update_format
    git_commit: cdc99cc66683ebbfcfb3ab758453f702b88f31d9
  
  

