submodules:
  - name: Imagine_Tool
    git_url: https://github.com/ImagineJHY/Imagine_Tool.git
    git_branch: ImagineTool/main
    git_commit: ffb985f5c4cbb84926856f05a852a636e8024c6c
    
  - name: Imagine_Muduo
    git_url: git@github.com:ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/update_code
    git_commit: e2f0e87b1e93a19a8f8470f3f8c050e266fc2cd0

  - name: Imagine_ZooKeeper
    git_url: git@github.com:ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/adapt_tool
    git_commit: f3cd89bf849aa1031c99a62a1e8ccc4e286b6a55

  - name: Imagine_Rpc
    git_url: git@github.com:ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/update_format
    git_commit: a6b4746f43ed346d881db36300ec38ba0bbdf1b8
  
  - name: Imagine_MapReduce
    git_url: git@github.com:ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/update_format
    git_commit: 01eb5390494053fd593f8bc122929b6a04f17941