submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo.git
    git_branch: ImagineMuduo/init_statemachine
    git_commit: d65f562a2e86318f85d51604854d75657cd102d9 

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper.git
    git_branch: ImagineZooKeeper/init_statemachine
    git_commit: 2308c5c67cade9dceb23b621bdd3181569c3bb36

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc.git
    git_branch: ImagineRpc/service_generator
    git_commit: fbc4cfe9e0e790875a506f2ff632213858700615
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce.git
    git_branch: ImagineMapReduce/init_map_threadpool
    git_commit: e81b661a4e32afa26989fd6d0d00b4742b11ac6b