submodules:
  - name: Imagine_Muduo
    git_url: https://github.com/ImagineJHY/Imagine_Muduo
    git_branch: ImagineMuduo/main
    git_commit: d1ecd5f56eeb978069af6f69800f728a47b7e6a6

  - name: Imagine_ZooKeeper
    git_url: https://github.com/ImagineJHY/Imagine_ZooKeeper
    git_branch: ImagineZooKeeper/main
    git_commit: 73558355057c5d7e8d3ac7df3890a8199bfe35d8

  - name: Imagine_Rpc
    git_url: https://github.com/ImagineJHY/Imagine_Rpc
    git_branch: ImagineRpc/main
    git_commit: eb0df919cab252cd4d96bc9885eb1a1d8ae06f5d
  
  - name: Imagine_MapReduce
    git_url: https://github.com/ImagineJHY/Imagine_MapReduce
    git_branch: ImagineMapReduce/main
    git_commit: 5cc6e2521dd5c6976fcd506b9c96fe6bf56acfe6
  
  

